#!/usr/bin/env bash

alias reload='source ~/.config/bash/aliases'

function ht() {
  history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head
}

function ef() {
  echo; for dir in ./*; do (echo "======== $dir ========"; echo; cd "$dir" && "$@"); echo; done
}

function realpath() {
  /usr/bin/python -c "import os,sys; print os.path.realpath(sys.argv[1])" "$0";
}

# Pathing
alias ..='cd ..;'
alias ...='.. ..'

# ssh
alias list-ssh='ps ax | grep "ssh" | grep -v grep'
alias list-t='ps ax | grep "ssh.*[0-9]:.*:[0-9]"'
alias path.list="echo \"\${PATH//:/\$'\n'}\""

# process status
alias tu='top -o cpu'
alias tm='top -o vsize'

# ls aliases
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -lh'
alias la='ls $LS_OPTIONS -lAh'
alias ld='ls $LS_OPTIONS -lad */'
alias lf='ls $LS_OPTIONS -ap | grep -v /'

#tail
alias t='tail'
alias tf='tail -F'

# some more ls aliases
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# custom aliases
alias upup="sudo apt update && sudo apt upgrade"
alias pua="pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias jkyll="bundle exec jekyll"
alias vactivate="conda deactivate && source venv/bin/activate"

function ikernel() {
  python -m ipykernel install --user --name="$1"
}

function sagtag() {
  if test "$#" -gt 1; then
    echo -e "usage $0 [date]"
    return
  elif test -n "$1"; then
    tagdate="$1"
  else
    tagdate="$(date)"
  fi
  date -d "$tagdate" +"%d of %B is day %-j of %Y in week %-V"
}
