#!/usr/bin/env bash

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# if running bash
if [ -n "$BASH_VERSION" ]; then
  # run bashrc if present
  test -f ~/.bashrc && . $_
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# include user global npm dir - added by Lukas
if [ -d "$HOME/.npm-global" ] ; then
    PATH="$HOME/.npm-global/bin:$PATH"
fi

# include user gem dir for Ruby gems
# Install Ruby Gems to ~/.gems
if [ -d "$HOME/.gems" ] ; then
    export GEM_HOME="$HOME/.gems"
    export PATH="$HOME/.gems/bin:$PATH"
fi
